server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userinfo?autoReconnect=true&maxReconnects=10&useUnicode=true&characterEncoding=utf8
    username: root
    password: xxxxxx
mybatis:
  type-aliases-package: com.thanos.springboot.bo
  mapper-locations: classpath*:mappers/**/*.xml

