server:
  port: 8080
  context-path: /ssb
flyway:
  enabled: false
spring:
  mvc:
    async:
      request-timeout: -1
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_info?autoReconnect=true&maxReconnects=10&useUnicode=true&characterEncoding=utf8
    username: root
    password: solarknight
    hikari:
      autoCommit: true
      connectionTimeout: 30000
      idleTimeout: 300000
      maxLifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 100
      connectionTestQuery: select 1
      leakDetectionThreshold: 30000
  redis:
    database: 0
    password:
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1
    host: 127.0.0.1
    port: 6379
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic