server:
  port: 8080
  context-path: /ssb
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_info?autoReconnect=true&maxReconnects=10&useUnicode=true&characterEncoding=utf8
    username: root
    password: solarknight
  redis:
    database: 0
    password:
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 1
    host: 127.0.0.1
    port: 6379
mybatis:
  type-aliases-package: com.thanos.springboot.bo
  mapper-locations: classpath*:mappers/**/*.xml
logging:
    config: classpath:logback/logback-spring.xml
