CREATE TABLE `user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `name` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'name',
  `sex` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '0 man, 1 woman',
  `descp` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'description',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='user table';
